### ISSUE TITLE
Generating HttpResponse from CacheData when there isn't a cache hit

### ISSUE THREAD

**Issue by robianmcd** [Cimpress-MCP/dotnet-core-httputils#6]
Great library! I'm just reading through it to understand how it works and I had a question. On this line: https://github.com/Cimpress-MCP/dotnet-core-httputils/blob/master/src/Cimpress.Extensions.Http.Caching.InMemory/InMemoryCacheHandler.cs#L61 why are you generating HttpResponse from the Cache data as opposed to just returning `response`?

Thanks

**Comment by thoean** [comment]
This would cause two problems, multiple usage and concurrency.
- _Multiple usage:_ If we'd just cache the `HttpResponse`, we'd reuse the same stream from `HttpResponse.Content` over and over again. Streams are meant to be read once, especially network streams. Also, consumers of a stream typically dispose it after using it, so even if it could be read multiple times, it won't be around anymore after the first call to `Dispose`.
- _Concurrency:_ The multiple usage problem aside, we could convert the network stream to a memory stream since that can be read multiple times. However, streams have state with the `Position` property, which would be shared among consumers. So multiple concurrent reads to the same stream would end with unpredictable behavior. (I haven't actually tested that problem.)

With that, we settled to [put everything into a simple byte array](https://github.com/Cimpress-MCP/dotnet-core-httputils/blob/master/src/Cimpress.Extensions.Http.Caching.InMemory/HttpResponseMessageExtensions.cs#L18) at time of caching and [create a copy of it with every response](https://github.com/Cimpress-MCP/dotnet-core-httputils/blob/master/src/Cimpress.Extensions.Http.Caching.InMemory/InMemoryCacheHandler.cs#L77).

**Edit:**
I misread the exact line you pointed out, your question was more about when we have a cache hit. However, it follows along above explanation. When we put the `HttpResponse.Content` into the cache, we already read the stream once and if we'd return the response directly, that stream would already have reached the end.

**Comment by robianmcd** [comment]
Ah ok. Makes sense. Thanks for the info!
